import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-d1-sqlite'

const MOCK_PROGRAMS = [
  {
    name: 'Christian Entrepreneurs Network - Los Angeles',
    religiousAffiliation: 'protestant',
    address: '1234 Wilshire Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90017',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'info@cenla.org',
    contactPhone: '(213) 555-0101',
    website: 'https://cenla.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Catholic Business Leaders Forum - New York',
    religiousAffiliation: 'catholic',
    address: '500 Fifth Avenue',
    city: 'New York',
    state: 'NY',
    zipCode: '10110',
    coordinates: { lat: 40.7549, lng: -73.9840 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'contact@cblf-ny.org',
    contactPhone: '(212) 555-0102',
    website: 'https://cblf-ny.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Faith & Business Small Group - Austin',
    religiousAffiliation: 'protestant',
    address: '789 Congress Ave',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    coordinates: { lat: 30.2672, lng: -97.7431 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'hello@faithbiz-atx.com',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Kingdom Business Network - Chicago',
    religiousAffiliation: 'protestant',
    address: '200 E Randolph St',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    coordinates: { lat: 41.8781, lng: -87.6298 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'info@kbn-chicago.org',
    contactPhone: '(312) 555-0103',
    website: 'https://kbn-chicago.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Catholic Professionals Online Fellowship',
    religiousAffiliation: 'catholic',
    address: '100 Virtual Plaza',
    city: 'Denver',
    state: 'CO',
    zipCode: '80202',
    coordinates: { lat: 39.7392, lng: -104.9903 },
    meetingFormat: 'online',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'fellowship@catpro.org',
    website: 'https://catpro-online.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Seattle Christian Business Roundtable',
    religiousAffiliation: 'protestant',
    address: '1500 Fourth Ave',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    coordinates: { lat: 47.6062, lng: -122.3321 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'info@scbr.org',
    contactPhone: '(206) 555-0104',
    website: 'https://scbr.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Phoenix Faith in the Workplace',
    religiousAffiliation: 'protestant',
    address: '2400 E Arizona Biltmore Cir',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85016',
    coordinates: { lat: 33.4484, lng: -112.0740 },
    meetingFormat: 'both',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'contact@phxfaith.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Boston Catholic Executives Circle',
    religiousAffiliation: 'catholic',
    address: '1 Federal St',
    city: 'Boston',
    state: 'MA',
    zipCode: '02110',
    coordinates: { lat: 42.3601, lng: -71.0589 },
    meetingFormat: 'in-person',
    meetingFrequency: 'quarterly',
    meetingLength: '4-8',
    meetingType: 'forum',
    averageAttendance: '100+',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'executives@bostoncec.org',
    contactPhone: '(617) 555-0105',
    website: 'https://bostoncec.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Miami Christian Marketplace Leaders',
    religiousAffiliation: 'protestant',
    address: '1101 Brickell Ave',
    city: 'Miami',
    state: 'FL',
    zipCode: '33131',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'hello@miamicml.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Portland Faith & Commerce Network',
    religiousAffiliation: 'protestant',
    address: '1000 SW Broadway',
    city: 'Portland',
    state: 'OR',
    zipCode: '97205',
    coordinates: { lat: 45.5152, lng: -122.6784 },
    meetingFormat: 'both',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'info@pdxfaith.com',
    website: 'https://pdxfaith.com',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Dallas Catholic Business Network',
    religiousAffiliation: 'catholic',
    address: '1910 Pacific Ave',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    coordinates: { lat: 32.7767, lng: -96.7970 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'network@dallascbn.org',
    contactPhone: '(214) 555-0106',
    website: 'https://dallascbn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Atlanta Kingdom Entrepreneurs',
    religiousAffiliation: 'protestant',
    address: '191 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30303',
    coordinates: { lat: 33.7490, lng: -84.3880 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'info@atlke.org',
    contactPhone: '(404) 555-0107',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'San Diego Faith-Based Business Forum',
    religiousAffiliation: 'protestant',
    address: '750 B St',
    city: 'San Diego',
    state: 'CA',
    zipCode: '92101',
    coordinates: { lat: 32.7157, lng: -117.1611 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'forum@sdfbf.org',
    website: 'https://sdfbf.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Minneapolis Christian Professional Network',
    religiousAffiliation: 'protestant',
    address: '800 Nicollet Mall',
    city: 'Minneapolis',
    state: 'MN',
    zipCode: '55402',
    coordinates: { lat: 44.9778, lng: -93.2650 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'connect@mplscpn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'St. Louis Catholic Commerce Guild',
    religiousAffiliation: 'catholic',
    address: '1 Metropolitan Sq',
    city: 'St. Louis',
    state: 'MO',
    zipCode: '63102',
    coordinates: { lat: 38.6270, lng: -90.1994 },
    meetingFormat: 'in-person',
    meetingFrequency: 'quarterly',
    meetingLength: '4-8',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'guild@stlccg.org',
    contactPhone: '(314) 555-0108',
    website: 'https://stlccg.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Nashville Faith-Driven Founders',
    religiousAffiliation: 'protestant',
    address: '150 Fourth Ave N',
    city: 'Nashville',
    state: 'TN',
    zipCode: '37219',
    coordinates: { lat: 36.1627, lng: -86.7816 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'founders@nashfdf.org',
    website: 'https://nashfdf.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Tampa Bay Christian Business Coalition',
    religiousAffiliation: 'protestant',
    address: '100 N Tampa St',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33602',
    coordinates: { lat: 27.9506, lng: -82.4572 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'coalition@tbcbc.org',
    contactPhone: '(813) 555-0109',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Pittsburgh Catholic Professionals',
    religiousAffiliation: 'catholic',
    address: '600 Grant St',
    city: 'Pittsburgh',
    state: 'PA',
    zipCode: '15219',
    coordinates: { lat: 40.4406, lng: -79.9959 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'professionals@pghcp.org',
    website: 'https://pghcp.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Charlotte Kingdom Business Collective',
    religiousAffiliation: 'protestant',
    address: '301 S Tryon St',
    city: 'Charlotte',
    state: 'NC',
    zipCode: '28202',
    coordinates: { lat: 35.2271, lng: -80.8431 },
    meetingFormat: 'both',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'info@cltkbc.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Indianapolis Faith in Business Leaders',
    religiousAffiliation: 'protestant',
    address: '1 Monument Cir',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46204',
    coordinates: { lat: 39.7684, lng: -86.1581 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'none',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'leaders@indyfibl.org',
    contactPhone: '(317) 555-0110',
    website: 'https://indyfibl.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'San Francisco Catholic Entrepreneurs',
    religiousAffiliation: 'catholic',
    address: '555 California St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94104',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '1-2',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'annual',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'entrepreneurs@sfce.org',
    website: 'https://sfce.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Columbus Christian Commerce Network',
    religiousAffiliation: 'protestant',
    address: '41 S High St',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43215',
    coordinates: { lat: 39.9612, lng: -82.9988 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'network@columcccn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'San Antonio Faith-Based Leaders Forum',
    religiousAffiliation: 'catholic',
    address: '100 E Houston St',
    city: 'San Antonio',
    state: 'TX',
    zipCode: '78205',
    coordinates: { lat: 29.4241, lng: -98.4936 },
    meetingFormat: 'in-person',
    meetingFrequency: 'quarterly',
    meetingLength: '4-8',
    meetingType: 'forum',
    averageAttendance: '100+',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'forum@safblf.org',
    contactPhone: '(210) 555-0111',
    website: 'https://safblf.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Milwaukee Christian Marketplace Ministries',
    religiousAffiliation: 'protestant',
    address: '633 W Wisconsin Ave',
    city: 'Milwaukee',
    state: 'WI',
    zipCode: '53203',
    coordinates: { lat: 43.0389, lng: -87.9065 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'ministries@mkecmm.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Kansas City Faith & Work Alliance',
    religiousAffiliation: 'protestant',
    address: '1100 Walnut St',
    city: 'Kansas City',
    state: 'MO',
    zipCode: '64106',
    coordinates: { lat: 39.0997, lng: -94.5786 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'alliance@kcfwa.org',
    website: 'https://kcfwa.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Las Vegas Catholic Business Fellowship',
    religiousAffiliation: 'catholic',
    address: '3730 S Las Vegas Blvd',
    city: 'Las Vegas',
    state: 'NV',
    zipCode: '89158',
    coordinates: { lat: 36.1699, lng: -115.1398 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'fellowship@lvgcbf.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Cleveland Christian Executive Roundtable',
    religiousAffiliation: 'protestant',
    address: '50 Public Sq',
    city: 'Cleveland',
    state: 'OH',
    zipCode: '44113',
    coordinates: { lat: 41.4993, lng: -81.6944 },
    meetingFormat: 'in-person',
    meetingFrequency: 'quarterly',
    meetingLength: '4-8',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'roundtable@clecert.org',
    contactPhone: '(216) 555-0112',
    website: 'https://clecert.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Cincinnati Faith in Commerce Group',
    religiousAffiliation: 'catholic',
    address: '312 Walnut St',
    city: 'Cincinnati',
    state: 'OH',
    zipCode: '45202',
    coordinates: { lat: 39.1031, lng: -84.5120 },
    meetingFormat: 'both',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'group@cincficg.org',
    website: 'https://cincficg.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Raleigh Kingdom Professionals Network',
    religiousAffiliation: 'protestant',
    address: '400 Fayetteville St',
    city: 'Raleigh',
    state: 'NC',
    zipCode: '27601',
    coordinates: { lat: 35.7796, lng: -78.6382 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'network@ralkpn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Detroit Christian Business Builders',
    religiousAffiliation: 'protestant',
    address: '500 Griswold St',
    city: 'Detroit',
    state: 'MI',
    zipCode: '48226',
    coordinates: { lat: 42.3314, lng: -83.0458 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'builders@detcbb.org',
    contactPhone: '(313) 555-0113',
    website: 'https://detcbb.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Sacramento Faith & Enterprise Hub',
    religiousAffiliation: 'protestant',
    address: '980 9th St',
    city: 'Sacramento',
    state: 'CA',
    zipCode: '95814',
    coordinates: { lat: 38.5816, lng: -121.4944 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'hub@sacfeh.org',
    website: 'https://sacfeh.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Baltimore Catholic Commerce Circle',
    religiousAffiliation: 'catholic',
    address: '100 Light St',
    city: 'Baltimore',
    state: 'MD',
    zipCode: '21202',
    coordinates: { lat: 39.2904, lng: -76.6122 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '1-2',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'circle@baltccc.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Salt Lake City Faith-Driven Business',
    religiousAffiliation: 'protestant',
    address: '50 W Broadway',
    city: 'Salt Lake City',
    state: 'UT',
    zipCode: '84101',
    coordinates: { lat: 40.7608, lng: -111.8910 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'business@slcfdb.org',
    website: 'https://slcfdb.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Richmond Christian Leaders Forum',
    religiousAffiliation: 'protestant',
    address: '919 E Main St',
    city: 'Richmond',
    state: 'VA',
    zipCode: '23219',
    coordinates: { lat: 37.5407, lng: -77.4360 },
    meetingFormat: 'in-person',
    meetingFrequency: 'quarterly',
    meetingLength: '4-8',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'forum@rvaclf.org',
    contactPhone: '(804) 555-0114',
    website: 'https://rvaclf.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'New Orleans Catholic Professionals League',
    religiousAffiliation: 'catholic',
    address: '601 Poydras St',
    city: 'New Orleans',
    state: 'LA',
    zipCode: '70130',
    coordinates: { lat: 29.9511, lng: -90.0715 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'league@nolacpl.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Tucson Faith & Work Fellowship',
    religiousAffiliation: 'protestant',
    address: '110 E Congress St',
    city: 'Tucson',
    state: 'AZ',
    zipCode: '85701',
    coordinates: { lat: 32.2226, lng: -110.9747 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'fellowship@tucfwf.org',
    website: 'https://tucfwf.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Oklahoma City Kingdom Business Alliance',
    religiousAffiliation: 'protestant',
    address: '100 Park Ave',
    city: 'Oklahoma City',
    state: 'OK',
    zipCode: '73102',
    coordinates: { lat: 35.4676, lng: -97.5164 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'alliance@okckba.org',
    contactPhone: '(405) 555-0115',
    website: 'https://okckba.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Memphis Christian Entrepreneurs Circle',
    religiousAffiliation: 'protestant',
    address: '5100 Poplar Ave',
    city: 'Memphis',
    state: 'TN',
    zipCode: '38137',
    coordinates: { lat: 35.1495, lng: -90.0490 },
    meetingFormat: 'both',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'circle@memcec.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Louisville Faith in the Marketplace',
    religiousAffiliation: 'catholic',
    address: '400 W Market St',
    city: 'Louisville',
    state: 'KY',
    zipCode: '40202',
    coordinates: { lat: 38.2527, lng: -85.7585 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'marketplace@loufitm.org',
    website: 'https://loufitm.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Albuquerque Christian Commerce Collaborative',
    religiousAffiliation: 'protestant',
    address: '201 3rd St NW',
    city: 'Albuquerque',
    state: 'NM',
    zipCode: '87102',
    coordinates: { lat: 35.0844, lng: -106.6504 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'collaborative@abqccc.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Fresno Faith-Based Professionals Network',
    religiousAffiliation: 'protestant',
    address: '2600 Fresno St',
    city: 'Fresno',
    state: 'CA',
    zipCode: '93721',
    coordinates: { lat: 36.7378, lng: -119.7871 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'annual',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'network@frefbpn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Omaha Catholic Business Leaders',
    religiousAffiliation: 'catholic',
    address: '1620 Dodge St',
    city: 'Omaha',
    state: 'NE',
    zipCode: '68102',
    coordinates: { lat: 41.2565, lng: -95.9345 },
    meetingFormat: 'in-person',
    meetingFrequency: 'quarterly',
    meetingLength: '4-8',
    meetingType: 'forum',
    averageAttendance: '50-100',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'leaders@omacbl.org',
    contactPhone: '(402) 555-0116',
    website: 'https://omacbl.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Boise Christian Marketplace Collective',
    religiousAffiliation: 'protestant',
    address: '150 N Capitol Blvd',
    city: 'Boise',
    state: 'ID',
    zipCode: '83702',
    coordinates: { lat: 43.6150, lng: -116.2023 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'collective@boicmc.org',
    website: 'https://boicmc.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Buffalo Faith & Commerce Network',
    religiousAffiliation: 'catholic',
    address: '257 W Genesee St',
    city: 'Buffalo',
    state: 'NY',
    zipCode: '14202',
    coordinates: { lat: 42.8864, lng: -78.8784 },
    meetingFormat: 'both',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'network@buffcn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Des Moines Kingdom Professionals',
    religiousAffiliation: 'protestant',
    address: '666 Grand Ave',
    city: 'Des Moines',
    state: 'IA',
    zipCode: '50309',
    coordinates: { lat: 41.5868, lng: -93.6250 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'small-group',
    averageAttendance: '1-10',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: false,
    contactEmail: 'professionals@dsmkp.org',
    contactPhone: '(515) 555-0117',
    website: 'https://dsmkp.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Little Rock Christian Executive Forum',
    religiousAffiliation: 'protestant',
    address: '500 President Clinton Ave',
    city: 'Little Rock',
    state: 'AR',
    zipCode: '72201',
    coordinates: { lat: 34.7465, lng: -92.2896 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'forum',
    averageAttendance: '20-50',
    hasConferences: 'annual',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'forum@lrcef.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Spokane Faith in Business Alliance',
    religiousAffiliation: 'protestant',
    address: '421 W Riverside Ave',
    city: 'Spokane',
    state: 'WA',
    zipCode: '99201',
    coordinates: { lat: 47.6588, lng: -117.4260 },
    meetingFormat: 'both',
    meetingFrequency: 'weekly',
    meetingLength: '1-2',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'none',
    hasOutsideSpeakers: false,
    hasEducationTraining: false,
    contactEmail: 'alliance@spokfiba.org',
    website: 'https://spokfiba.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Worcester Catholic Entrepreneurs Network',
    religiousAffiliation: 'catholic',
    address: '446 Main St',
    city: 'Worcester',
    state: 'MA',
    zipCode: '01608',
    coordinates: { lat: 42.2626, lng: -71.8023 },
    meetingFormat: 'in-person',
    meetingFrequency: 'monthly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '10-20',
    hasConferences: 'annual',
    hasOutsideSpeakers: false,
    hasEducationTraining: true,
    contactEmail: 'entrepreneurs@worcen.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
  {
    name: 'Grand Rapids Christian Business Network',
    religiousAffiliation: 'protestant',
    address: '161 Ottawa Ave NW',
    city: 'Grand Rapids',
    state: 'MI',
    zipCode: '49503',
    coordinates: { lat: 42.9634, lng: -85.6681 },
    meetingFormat: 'in-person',
    meetingFrequency: 'weekly',
    meetingLength: '2-4',
    meetingType: 'peer-group',
    averageAttendance: '20-50',
    hasConferences: 'multiple',
    hasOutsideSpeakers: true,
    hasEducationTraining: true,
    contactEmail: 'network@grcbn.org',
    contactPhone: '(616) 555-0118',
    website: 'https://grcbn.org',
    sourceUrl: 'MOCK_SEED_DATA',
  },
]

export async function up({ payload }: MigrateUpArgs): Promise<void> {
  console.log('Seeding 50 mock programs...')

  for (const program of MOCK_PROGRAMS) {
    await payload.create({
      collection: 'programs',
      data: program as any,
    })
  }

  console.log('Successfully seeded 50 mock programs')
}

export async function down({ payload }: MigrateDownArgs): Promise<void> {
  console.log('Removing mock programs...')

  const mockPrograms = await payload.find({
    collection: 'programs',
    where: {
      sourceUrl: {
        equals: 'MOCK_SEED_DATA',
      },
    },
    limit: 1000, // Ensure we get all mock programs
  })

  for (const program of mockPrograms.docs) {
    await payload.delete({
      collection: 'programs',
      id: program.id,
    })
  }

  console.log(`Successfully removed ${mockPrograms.docs.length} mock programs`)
}
